spring:
  application:
    name: DISCOVERY-SERVICE

  security:
    user:
      name: eureka
      password: password

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: false

